#!/bin/bash

OS_NAME="$(uname | awk '{print tolower($0)}')"

SHELL_DIR=$(dirname $0)

RUN_PATH="."

CMD=${1:-$CIRCLE_JOB}

PARAM=${2}

USERNAME=${GITHUB_ACTOR}
REPONAME=${GITHUB_REPOSITORY}

GITHUB_TOKEN=${GITHUB_TOKEN}

DOCKER_USER=${DOCKER_USER:-$USERNAME}
DOCKER_PASS=${DOCKER_PASS}

SLACK_TOKEN=${SLACK_TOKEN}
