#!/bin/bash

############################################################

function usage() {
  echo "Usage: $0 {host} {port} {username}"
}

############################################################

BASEDIR=$(dirname $0)
cd ${BASEDIR}

HOST=$1
PORT=$2
USER=$3

CMD=$4
SUB=$5

ARTIFACT=$6
VERSION=$7
TYPE=$8
PATH=$9

if [ "${USER}" == "" ]; then
  usage
  exit 1
fi

PARAM="${CMD} ${SUB} ${ARTIFACT} ${VERSION} ${TYPE} ${PATH}"

ssh ${USER}@${HOST} -p ${PORT} 'bash -s' < toast ${PARAM}

exit $?
