#!/bin/bash

############################################################

function usage() {
  echo "Usage: $0 {username} {host} {port:22}"
}

############################################################

BASEDIR=$(dirname $0)
cd ${BASEDIR}

USER=${1}
SERVER=${2}
PORT=${3}

CMD=${4}
SUB=${5}

GROUP_ID=${6}
ARTIFACT_ID=${7}
VERSION=${8}
TYPE=${9}
DOMAIN=${10}

if [ "${SERVER}" == "" ]; then
  usage
  exit 1
fi

if [ "${PORT}" == "" ]; then
  PORT=22
fi

COMMAND="~/toaster/toast ${CMD} ${SUB} ${GROUP_ID} ${ARTIFACT_ID} ${VERSION} ${TYPE} ${DOMAIN}"

ssh ${USER}@${SERVER} -p ${PORT} "${COMMAND}"

# ~/toaster/remote user ip 22 deploy fleet
# ~/toaster/remote user ip 22 deploy project com.yanolja yanolja.deploy 0.0.2 php deploy.yanolja.com
