#!/bin/bash

################################################################################

SELF_URL="http://toast.yanolja.com/toaster/toast"

TOAST_URL="http://toast.yanolja.com"

LOGIN_URL="https://member.yanolja.com/ywt/loginToken"

REPO_PATH="http://toast.yanolja.com/uploads/com/yanolja"
REPO_USER=""
REPO_PASS=""

PHASE="dev"
FLEET="dev"
NAME=`hostname`

SNO=""

HOST="127.0.0.1"
PORT="22"

USER="yanolja"

TOKEN=""

CONFIG="${HOME}/.toast"

if [ -f "${CONFIG}" ]; then
  . ${CONFIG}
fi

################################################################################

CMD=$1
SUB=$2

ARTIFACT_ID=$3
VERSION=$4
DEPLOY_TYPE=$5
DEPLOY_PATH=$6

HAS_WAR=FALSE

SUDO=""

if [ ${HOME} != "/root" ]; then
    SUDO="sudo"
fi

SHELL_DIR=$(dirname $0)

TEMP_DIR="/tmp/deploy"

if [ ! -d "${TEMP_DIR}" ]; then
    mkdir "${TEMP_DIR}"
fi

################################################################################

toast() {
    self_update

    case ${CMD} in
        self)
            self
            ;;
        config)
            config
            ;;
        init)
            init
            ;;
        version)
            version
            ;;
        deploy)
            deploy
            ;;
        *)
            usage
    esac

    if [ ! -f "${CONFIG}" ]; then
        config
    fi
}

usage() {
    echo_bar
    echo " Usage: toast {self|config|init|version|deploy}"
    echo_bar
    echo_
    echo " Usage: toast self"
    echo_
    echo " Usage: toast config"
    echo " Usage: toast config info"
    echo_
    echo " Usage: toast init"
    echo " Usage: toast init update"
    echo " Usage: toast init master"
    echo " Usage: toast init slave"
    echo " Usage: toast init web"
    echo " Usage: toast init db"
    echo_
    echo " Usage: toast version"
    echo " Usage: toast version next"
    echo " Usage: toast version save"
    echo_
    echo " Usage: toast deploy"
    echo " Usage: toast deploy vhost"
    echo " Usage: toast deploy server"
    echo " Usage: toast deploy project"
    echo_
    echo_bar
}

self() {
    self_info

    case ${SUB} in
        update)
            self_update
            ;;
    esac
}

config() {
    case ${SUB} in
        info|echo|show)
            config_info
            ;;
        *)
            config_read
    esac
}

init() {
    init_default

    case ${SUB} in
        update)
            init_update
            ;;
        master)
            init_master
            ;;
        slave)
            init_slave
            ;;
        web|apache|php)
            init_web
            ;;
        db|mysql)
            init_db
            ;;
    esac
}

version() {
    version_parse

    case ${SUB} in
        next)
            version_next
            ;;
        save)
            version_save
            ;;
    esac
}

deploy() {
    case ${SUB} in
        vhost)
            deploy_vhost
            ;;
        project)
            deploy_project
            ;;
        server)
            deploy_server
            ;;
    esac
}

################################################################################

self_info() {
    echo_bar

    echo "PATH : $0"
    echo "HOME : ${HOME}"

    echo_bar
}

self_update() {
    pushd "${SHELL_DIR}"
    git pull
    popd
}

login() {
    echo "Please input yanolja id."
    read YAJA_ID
    if [ "${YAJA_ID}" == "" ]; then
        exit 1
    fi

    echo "Please input yanolja password."
    read YAJA_PW
    if [ "${YAJA_PW}" == "" ]; then
        exit 1
    fi

    echo "yanolja login..."

    RES=`curl --data "id=${YAJA_ID}&passwd=${YAJA_PW}" ${LOGIN_URL}`
    ARR=(${RES})

    TOKEN="${ARR[0]}"
}

config_read() {
    if [ "${TOKEN}" == "" ]; then
        login
    else
        echo "Do you want yanolja login? [yes/no] [default:no]"
        read LOGIN_YN
        if [ "${LOGIN_YN}" == "yes" ]; then
            login
        fi
    fi

    echo "Please input toast url. [default:${TOAST_URL}]"
    read READ_TOAST_URL
    if [ "${READ_TOAST_URL}" != "" ]; then
        TOAST_URL=${READ_TOAST_URL}
    fi

    echo "Please input server phase. [default:${PHASE}]"
    read READ_PHASE
    if [ "${READ_PHASE}" != "" ]; then
        PHASE=${READ_PHASE}
    fi

    echo "Please input server fleet. [default:${FLEET}]"
    read READ_FLEET
    if [ "${READ_FLEET}" != "" ]; then
        FLEET=${READ_FLEET}
    fi

    echo "Please input server name. [default:${NAME}]"
    read READ_NAME
    if [ "${READ_NAME}" != "" ]; then
        NAME=${READ_NAME}
    fi

    echo "Please input server host. [default:${HOST}]"
    read READ_HOST
    if [ "${READ_HOST}" != "" ]; then
        HOST=${READ_HOST}
    fi

    echo "Please input server port. [default:${PORT}]"
    read READ_PORT
    if [ "${READ_PORT}" != "" ]; then
        PORT=${READ_PORT}
    fi

    echo "Please input server user. [default:${USER}]"
    read READ_USER
    if [ "${READ_USER}" != "" ]; then
        USER=${READ_USER}
    fi

    echo "# yanolja toast config" > ${CONFIG}
    echo "TOAST_URL=${TOAST_URL}" >> ${CONFIG}
    echo "REPO_PATH=${REPO_PATH}" >> ${CONFIG}
    echo "REPO_USER=${REPO_USER}" >> ${CONFIG}
    echo "REPO_PASS=${REPO_PASS}" >> ${CONFIG}
    echo "PHASE=${PHASE}" >> ${CONFIG}
    echo "FLEET=${FLEET}" >> ${CONFIG}
    echo "NAME=${NAME}" >> ${CONFIG}
    echo "HOST=${HOST}" >> ${CONFIG}
    echo "PORT=${PORT}" >> ${CONFIG}
    echo "USER=${USER}" >> ${CONFIG}
    echo "TOKEN=${TOKEN}" >> ${CONFIG}

    config_save
}

config_info() {
    if [ ! -f "${CONFIG}" ]; then
        echo "Not exist file. [${CONFIG}]"
        exit 1
    fi

    echo_bar
    cat ${CONFIG}
    echo_bar
}

config_save() {
    echo "server save..."

    URL="${TOAST_URL}/server/config"
    RES=`curl --data "token=${TOKEN}&group=${PHASE}&fleet=${FLEET}&name=${NAME}&host=${HOST}&port=${PORT}&user=${USER}" ${URL}`
    ARR=(${RES})

    if [ "${ARR[0]}" != "OK" ]; then
        echo "Server Error."
        exit 1
    fi

    echo "SNO=${ARR[1]}" >> ${CONFIG}

    echo "${ARR[0]} ${ARR[1]}"
}

init_default() {
    if [ ! -f "/etc/localtime" ]; then
        ${SUDO} ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
    fi

    if [ ! -f "/usr/bin/git" ]; then
        ${SUDO} yum install -y git
    fi

    if [ ! -f "/usr/bin/vim" ]; then
        ${SUDO} yum install -y vim
    fi

    make_dir "${HOME}/.ssh"

    make_dir "/data"
    make_dir "/data/logs"
}

init_update() {
    ${SUDO} yum update -y
}

init_master() {
    KEYS="${HOME}/.ssh/authorized_keys"

    if [ ! -f "${KEYS}" ]; then
        cat ${SHELL_DIR}/ssh/id_rsa.pub > ${KEYS}
        chmod 700 ${KEYS}
    else
        IS_KEY="false"

        while read line
        do
            VAL=(${line})

            if [ "${VAL[2]}" == "toast@yanolja.in" ]; then
                IS_KEY="true"
            fi
        done < ${KEYS}

        if [ "${IS_KEY}" == "false" ]; then
            cat ${SHELL_DIR}/ssh/id_rsa.pub >> ${KEYS}
        fi
    fi
}

init_slave() {
    ID_RSA="${HOME}/.ssh/id_rsa.pub"

    if [ ! -f "${ID_RSA}" ]; then
        #ssh-keygen -t rsa -C "toast@$yanolja.in"

        cp -rf ${SHELL_DIR}/ssh/id_rsa ${HOME}/.ssh/id_rsa
        cp -rf ${SHELL_DIR}/ssh/id_rsa.pub ${HOME}/.ssh/id_rsa.pub

        chmod 600 ${HOME}/.ssh/id_rsa
        chmod 644 ${HOME}/.ssh/id_rsa.pub
    fi
}

init_web() {
    ${SUDO} yum install -y httpd24 php56 php56-mysqlnd php56-mcrypt

    ${SUDO} service httpd start
    ${SUDO} chkconfig httpd on

    make_dir "/data/site"
}

init_db() {
    ${SUDO} yum install -y mysql55-server

    ${SUDO} service mysqld start
    ${SUDO} chkconfig mysqld on
}

version_parse() {
    DEST_FILE="./pom.xml"

    if [ ! -f "${DEST_FILE}" ]; then
        echo "Not exist file. [${DEST_FILE}]"
        exit 1
    fi

    ARR_GROUP=($(cat ${DEST_FILE} | grep -oP '(?<=groupId>)[^<]+'))
    ARR_ARTIFACT=($(cat ${DEST_FILE} | grep -oP '(?<=artifactId>)[^<]+'))
    ARR_VERSION=($(cat ${DEST_FILE} | grep -oP '(?<=version>)[^<]+'))

    if [ "${ARR_GROUP[0]}" == "" ]; then
        echo "groupId does not exist. [${ARR_GROUP[0]}]"
        exit 1
    fi
    if [ "${ARR_ARTIFACT[0]}" == "" ]; then
        echo "artifactId does not exist. [${ARR_ARTIFACT[0]}]"
        exit 1
    fi

    echo "groupId=${ARR_GROUP[0]}"
    echo "artifactId=${ARR_ARTIFACT[0]}"
    echo "version=${ARR_VERSION[0]}"

    ARTIFACT_ID=${ARR_GROUP[0]}
    VERSION=${ARR_VERSION[0]}
}

version_next() {
    echo "version get..."

    URL="${TOAST_URL}/version/latest/${ARTIFACT_ID}"
    RES=`curl --data "token=${TOKEN}" ${URL}`
    ARR=(${RES})

    if [ "${ARR[0]}" != "OK" ]; then
        echo "Server Error."
        exit 1
    fi

    NEXT_VERSION="${ARR[1]}"

    echo "${NEXT_VERSION}"

    VER1="<version>[\.0-9a-zA-Z]\+<\/version>"
    VER2="<version>${NEXT_VERSION}<\/version>"

    TEMP_FILE="/tmp/toast-pom.tmp.$$"

    if [ -f ${DEST_FILE} -a -r ${DEST_FILE} ]; then
        sed "s/$VER1/$VER2/;10q;" "${DEST_FILE}" > ${TEMP_FILE}
        sed "1,10d" "${DEST_FILE}" >> ${TEMP_FILE}

        mv ${TEMP_FILE} "${DEST_FILE}"
    else
        echo "Error - Read Fail : ${DEST_FILE}"
        exit 1
    fi

    VERSION=NEXT_VERSION
}

version_save() {
    echo "version save..."

    #aws s3 sync ~/.m2/repository/com/yanolja/${ARTIFACT_ID}/ s3://repo.yanolja.com/release/com/yanolja/${ARTIFACT_ID}/

    URL="${TOAST_URL}/version/build/${ARTIFACT_ID}/${VERSION}"
    RES=`curl --data "token=${TOKEN}" ${URL}`
    ARR=(${RES})

    if [ "${ARR[0]}" != "OK" ]; then
        echo "Server Error."
        exit 1
    fi

    echo "${ARR[1]}"
}

version_remove() {
    #aws s3 rm s3://repo.yanolja.com/release/com/yanolja/${ARTIFACT_ID}/${VERSION} --recursive

    rm -rf ~/.m2/repository/com/yanolja/${ARTIFACT_ID}/${VERSION}
}

deploy_vhost() {
    CONF_DIR="/etc/httpd/conf.d"

    if [ ! -d "${CONF_DIR}" ]; then
        echo "Need web server init. [toast init web]"
        exit 1
    fi

    ${SUDO} service httpd stop

    ${SUDO} rm -rf ${CONF_DIR}/localhost*
    ${SUDO} rm -rf ${CONF_DIR}/vhost*

    #${SUDO} cp "${SHELL_DIR}/vhost/localhost.conf" "${CONF_DIR}/"
    #${SUDO} chmod 644 "${CONF_DIR}/localhost.conf"

    TEMP_FILE="/tmp/toast-vhost.tmp.$$"

    TEMPLATE="${SHELL_DIR}/vhost/vhost-temp.conf"

    echo "download vhost..."

    TARGET_FILE="${TEMP_DIR}/${NAME}"
    ${SUDO} rm -rf "${TARGET_FILE}"

    URL="${TOAST_URL}/target/vhost/${PHASE}/${NAME}"
    wget -q -N -P "${TEMP_DIR}" "${URL}"

    while read line
    do
        TARGET=(${line})

        VNM="${TARGET[0]}"
        DOM="${TARGET[1]}"

        make_dir "/data/site/${VNM}"

        DEST_FILE="${CONF_DIR}/vhost-${VNM}.conf"

        echo "--> ${DEST_FILE}"

        ${SUDO} cp ${TEMPLATE} ${DEST_FILE}

        sed "s/VDIR/$VNM/g" ${DEST_FILE} > ${TEMP_FILE} && ${SUDO} mv ${TEMP_FILE} ${DEST_FILE}
        sed "s/VDOM/$DOM/g" ${DEST_FILE} > ${TEMP_FILE} && ${SUDO} mv ${TEMP_FILE} ${DEST_FILE}

        ${SUDO} chmod 644 "${DEST_FILE}"
    done < ${TARGET_FILE}

    ${SUDO} service httpd start
}

deploy_project() {
    # "deploy project yanolja.deploy 0.0.0 php /data/site/deploy"

    PACKAGING="${DEPLOY_TYPE}"
    if [ "${PACKAGING}" == "php" ]; then
        PACKAGING="war"
        DEPLOY_PATH="/data/site/${ARTIFACT_ID}"
    fi

    FILENAME="${ARTIFACT_ID}-${VERSION}.${PACKAGING}"
    FILEPATH="${TEMP_DIR}/${FILENAME}"

    UNZIP_DIR="${TEMP_DIR}/${ARTIFACT_ID}"

    echo "download..."

    download

    tomcat_stop

    echo "placement..."

    placement

    tomcat_start
}

deploy_server() {
    # "deploy server"

    echo "download target..."

    TARGET_FILE="${TEMP_DIR}/${NAME}"
    ${SUDO} rm -rf "${TARGET_FILE}"

    URL="${TOAST_URL}/target/server/${PHASE}/${NAME}"
    wget -q -N -P "${TEMP_DIR}" "${URL}"

    echo "download..."

    while read line
    do
      TARGET=(${line})

      deploy_value

      download
    done < ${TARGET_FILE}

    tomcat_stop

    echo "placement..."

    while read line
    do
      TARGET=(${line})

      deploy_value

      placement
    done < ${TARGET_FILE}

    tomcat_start
}

deploy_value() {
    ARTIFACT_ID="${TARGET[0]}"
    VERSION="${TARGET[1]}"
    DEPLOY_TYPE="${TARGET[2]}"
    DEPLOY_PATH="${TARGET[3]}"
    RANDOM="${TARGET[4]}"

    PACKAGING="${DEPLOY_TYPE}"
    if [ "${PACKAGING}" == "php" ]; then
        PACKAGING="war"
        DEPLOY_PATH="/data/site/${ARTIFACT_ID}"
    fi

    FILENAME="${ARTIFACT_ID}-${VERSION}.${PACKAGING}"
    FILEPATH="${TEMP_DIR}/${FILENAME}"

    UNZIP_DIR="${TEMP_DIR}/${RANDOM}"
}

download() {
    SOURCE="${REPO_PATH}/${ARTIFACT_ID}/${VERSION}/${FILENAME}"

    echo "--> from : ${SOURCE}"
    echo "--> to   : ${TEMP_DIR}/${FILENAME}"

    if [ -d "${FILEPATH}" ] || [ -f "${FILEPATH}" ]; then
        rm -rf "${FILEPATH}"
    fi

    if [ "${REPO_USER}" == "" ] || [ "${REPO_PASS}" == "" ]; then
        wget -q -N -P "${TEMP_DIR}" "${SOURCE}"
    else
        wget -q --user "${REPO_USER}" --password "${REPO_PASS}" -N -P "${TEMP_DIR}" "${SOURCE}"
    fi

    if [ ! -f "${FILEPATH}" ]; then
        echo "deploy file does not exist. [${FILEPATH}]"
        exit 1
    fi

    # war (for tomcat stop/start)
    if [ "${DEPLOY_TYPE}" == "war" ]; then
        HAS_WAR="TRUE"
    fi

    # php unzip
    if [ "${DEPLOY_TYPE}" == "php" ]; then
        if [ -d "${UNZIP_DIR}" ] || [ -f "${UNZIP_DIR}" ]; then
            rm -rf "${UNZIP_DIR}"
        fi

        if [ -d "${UNZIP_DIR}" ] || [ -f "${UNZIP_DIR}" ]; then
            echo "deploy file can not unzip. [${UNZIP_DIR}]"
            exit 1
        fi

        unzip -q "${FILEPATH}" -d "${UNZIP_DIR}"
    fi
}

placement() {
  if [ "${DEPLOY_PATH}" == "" ]; then
      echo "empty deploy path. [${DEPLOY_PATH}]"
      exit 1
  fi

  echo "--> ${DEPLOY_PATH}"

  # php
  if [ "${DEPLOY_TYPE}" == "php" ]; then
    rm -rf "${DEPLOY_PATH}.backup"

    if [ -d "${DEPLOY_PATH}" ] || [ -f "${DEPLOY_PATH}" ]; then
        mv "${DEPLOY_PATH}" "${DEPLOY_PATH}.backup"
    fi

    if [ -d "${DEPLOY_PATH}" ] || [ -f "${DEPLOY_PATH}" ]; then
      echo "deploy dir can not copy. [${DEPLOY_PATH}]"
      exit 1
    fi

    mv "${UNZIP_DIR}" "${DEPLOY_PATH}"
  fi

  # war
  if [ "${DEPLOY_TYPE}" == "war" ]; then
    DEST_WAR="${DEPLOY_PATH}/${ARTIFACT_ID}.${PACKAGING}"

    rm -rf "${DEPLOY_PATH}/${ARTIFACT_ID}"
    rm -rf "${DEST_WAR}"

    if [ -d "${DEST_WAR}" ] || [ -f "${DEST_WAR}" ]; then
      echo "deploy file can not copy. [${DEST_WAR}]"
      exit 1
    fi

    cp -rf "${FILEPATH}" "${DEST_WAR}"
  fi

  # jar
  if [ "${DEPLOY_TYPE}" == "jar" ]; then
    DEST_WAR="${DEPLOY_PATH}/${ARTIFACT_ID}.${PACKAGING}"

    process_stop

    rm -rf "${DEST_WAR}"

    if [ -d "${DEST_WAR}" ] || [ -f "${DEST_WAR}" ]; then
      echo "deploy file can not copy. [${DEST_WAR}]"
      exit 1
    fi

    cp -rf "${FILEPATH}" "${DEST_WAR}"

    process_start
  fi
}

tomcat_stop() {
    if [ "${HAS_WAR}" == "TRUE" ]; then
      echo "tomcat stop..."
      /usr/local/tomcat8/bin/shutdown.sh
    fi
}

tomcat_start() {
    if [ "${HAS_WAR}" == "TRUE" ]; then
      status=`ps -ef | grep catalina | grep java | grep -v grep | wc -l | awk '{print $1}'`
      count=0
      while [ ${status} -ge 1 ]; do
        echo "sleep..."
        sleep 3

        if [ ${count} -ge 5 ]; then
          pid=`ps -ef | grep catalina | grep java | grep -v grep | awk '{print $2}'`
          kill -9 ${pid}
          echo "tomcat (${pid}) was killed."
        fi

        sleep 2
        status=`ps -ef | grep catalina | grep java | grep -v grep | wc -l | awk '{print $1}'`
        count=`expr ${count} + 1`
      done
      echo "tomcat start..."
      /usr/local/tomcat8/bin/startup.sh
    fi
}

process_stop() {
    PID=`ps -ef | grep "[${ARTIFACT_ID:0:1}]""${ARTIFACT_ID:1}" | awk '{print $2}'`
    if [ "${PID}" != "" ]; then
      kill -9 ${PID}
      echo "killed ${PID}"
    fi
}

process_start() {
    java -jar ${DEPLOY_PATH}/${ARTIFACT_ID}.${PACKAGING} >> /dev/null &

    PID=`ps -ef | grep "[${ARTIFACT_ID:0:1}]""${ARTIFACT_ID:1}" | awk '{print $2}'`
    if [ "${PID}" != "" ]; then
      echo "start up ${PID}"
    fi
}

make_dir() {
    if [ ! -d $1 ] && [ ! -f $1 ]; then
        ${SUDO} mkdir $1
        ${SUDO} chown ${USER}.${USER} $1
    fi
}

echo_bar() {
    echo "================================================================================"
}

echo_() {
    echo ""
}

################################################################################

toast

# done
echo "done."

exit $?
